from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from agents.supervisor import run_supervisor
from routers.schemas import ChatResponse
import utils.db as db

router = APIRouter(tags=["chat"])

VALID_TICKERS = {
    "NVDA",
    "TSMC",
    "AAPL",
    "MSFT",
    "GOOGL",
    "META",
    "TSLA",
    "AMD",
    "INTC",
    "AMZN",
    "ASML",
    "ARM",
    "QCOM",
    "AVGO",
    "AMAT",
}


class ChatRequest(BaseModel):
    ticker: str = Field(
        ...,
        description="One of the 15 tracked tickers (case-insensitive).",
        examples=["NVDA"],
    )
    query: str = Field(
        ...,
        description="The user's natural-language question about the ticker.",
        examples=["What do analysts currently think about NVDA?"],
    )
    session_id: str = Field(
        ...,
        description="UUID generated by the frontend when a user selects a stock. Stable for the duration of that conversation; used to load and append chat history.",
        examples=["b3b1f6b0-6e9f-4b8b-9b0a-2f6f1a4c2e11"],
    )

    class Config:
        json_schema_extra = {
            "example": {
                "ticker": "NVDA",
                "query": "What do analysts think about NVDA and does recent news support that view?",
                "session_id": "b3b1f6b0-6e9f-4b8b-9b0a-2f6f1a4c2e11",
            }
        }


@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Ask the multi-agent chat a question about a ticker",
    description=(
        "Classifies query intent and invokes the Research Agent (live yfinance/SEC data), "
        "the RAG Agent (Pinecone semantic search), or both, then synthesizes an answer via "
        "Llama 4 Maverick (falling back to Llama 3.3 70B on failure). Prior turns for "
        "`session_id` are loaded from Postgres before answering, and both the user query "
        "and the assistant's answer are appended afterward."
    ),
)
async def chat(req: ChatRequest):
    ticker = req.ticker.upper()
    if ticker not in VALID_TICKERS:
        raise HTTPException(
            status_code=404, detail=f"{req.ticker} is not a tracked stock"
        )

    history = db.get_chat_history(req.session_id)
    result = await run_supervisor(ticker, req.query, history)

    db.append_chat_turn(req.session_id, ticker, "user", req.query)
    db.append_chat_turn(req.session_id, ticker, "assistant", result["answer"])

    return result
